View(bank)
dim(bank)
str(bank)
summary(bank)

completeFun <- function(data, desiredCols) {
  completeVec <- complete.cases(data[, desiredCols])
  return(data[completeVec, ])
}

processed<-bank[complete.cases(bank), ]
dim(processed)
boxplot(processed$age)
cor(processed$age,processed$balance)
cor(processed$age,processed$campaign)
cor(processed$age,processed$previous)
range(processed$age)
hist(processed$age)
hist(processed$previous)
hist(processed$campaign)
plot(x=processed$age,y=processed$previous,main="graph1",xlab="age",ylab="previous",xlim = c(1,100), ylim = c(1,10))
#plot(x=bank$age,y=bank$compaign,main="graph2",xlab="age",ylab="compaign",xlim = c(1,100), ylim = c(1,10))
#pairs(~bank$age+bank$balance+bank$day+bank$previous,main = "Scatterplot Matrix")
pairs(~processed$age+processed$previous+processed$campaign,main = "Scatterplot Matrix")
qplot(age,previous,data=processed)
qplot(age,campaign,data=processed)
d<-density(processed$age)
plot(d, main = "Kernel density of Age")
#polygon(d, col = "red", border = "blue")
d<-density(processed$campaign)
plot(d, main = "Kernel density of campaign")
#polygon(d, col = "red", border = "blue")
d<-density(processed$previous)
plot(d, main = "Kernel density of previous")
#polygon(d, col = "red", border = "blue")